### PR TITLE
Create master beta 2

### PR DESCRIPTION
**Pull request by rturrado**
### Added

- `.clang-format`.
- `emscripten-wasm` assets job.

### Changed

- Fix shared library build.

### Removed

- `TREEN_GEN_BUILD_TESTS` option.

### CODE REVIEW

**Comment by rturrado** [comment]
Most of the changes come from `clang-format`.

The only "real" changes are:

- `assets.yml`: add `emscripten-wasm` job.
- `src/CMakeLists.txt`: fix shared library build.
- `conanfile.py`: remove `TREE_GEN_BUILD_TESTS` option, and add `BUILD_SHARED_LIBS` option.
- `emscripten/test_cqasm.js`, `include/version.hpp`, `CHANGELOG.md`: update to version 0.6.2.
- `.clang-format`: add Clang format.

**Review by elenbaasc — COMMENTED** [review]
As you say, there are just some small changes. But why have so many files changed then? Are these generated?

**Review by elenbaasc — APPROVED** [review]

**Comment by elenbaasc** [comment]
We will keep the release 0.6.2. on PyPI then right, as it is identical to this PR?

**Comment by rturrado** [comment]
> We will keep the release 0.6.2. on PyPI then right, as it is identical to this PR?

That's it.

Hopefully, once Conan Center build system is back up running, we will also have a libqasm Conan package based off 0.6.2.

Remember also we have `master-beta-3` (0.6.3) ready for review, which implements multiple `measure` instructions at the end of the program.

**Pull request merged**
