### PR TITLE
Fix CXX requirements to require C++11

### PR DESCRIPTION
**Pull request by koffie**
Before this change I got errors like:

```
/code/qutech/libqasm/src/cqasm/tree-gen/include/tree-base.hpp.inc:1198:48: error: expected ';' at end of declaration
    Many<typename std::remove_const<T>::type> c{};
                                               ^
                                               ;
/code/qutech/libqasm/src/cqasm/tree-gen/include/tree-base.hpp.inc:1199:10: warning: 'auto' type specifier is a C++11 extension [-Wc++11-extensions]
    for (auto &sptr : this->vec) {
         ^

```
When building on my machine. It appears that this library was written against the C++11 version of the C++ standard.

This can be fixed by defining the required C++ version in the CMAKE file.

It might have build fine on other machines that already use C++11 by default.

### CODE REVIEW

**Review by wvlothuizen — COMMENTED** [review]
Looks good to me, and similar settings are present in OpenQL (which includes libqasm as subdirectory).

OpenQL also adds the following line, and it seems to makes sense to do the same here:
`set(CMAKE_CXX_EXTENSIONS OFF)`

**Comment by koffie** [comment]
> set(CMAKE_CXX_EXTENSIONS OFF)

Indeed adding this makes sense. My main focus with this commit was getting it to also work on my machine. However this extra option ensure more portability (at least if it still compiles). I just verified everything works fine with this addition.

**Review by tomrijnbeek — COMMENTED** [review]
Looks pretty uncontroversial to me. Could you please rebase this based on the latest develop commit to ensure this change still works at HEAD?

**Comment by koffie** [comment]
I created #144 with the rebase on develop since I don't like force pushing to public branches.

**Pull request closed without merging**
